### PR TITLE
update default envs to distributed 2021.12.0

### PR DESCRIPTION
**Pull request by matthiasdv**
The conda solve for the 3.9 env: 

```python
# packages in environment at /Users/matthiasdevriendt/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
abseil-cpp                20210324.2           he49afe7_0    conda-forge
aiobotocore               2.0.1              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h89e85a6_0    conda-forge
aioitertools              0.8.0              pyhd8ed1ab_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
arrow-cpp                 6.0.1           py39hf938c1e_7_cpu    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
aws-c-cal                 0.5.11               hd2e2f4b_0    conda-forge
aws-c-common              0.6.2                h0d85af4_0    conda-forge
aws-c-event-stream        0.2.7               hb9330a7_13    conda-forge
aws-c-io                  0.10.5               h35aa462_0    conda-forge
aws-checksums             0.1.11               h0010a65_7    conda-forge
aws-sdk-cpp               1.8.186              h766a74d_3    conda-forge
blosc                     1.21.0               he49afe7_0    conda-forge
bokeh                     2.4.2            py39h6e9494a_0    conda-forge
botocore                  1.22.8             pyhd8ed1ab_0    conda-forge
bottleneck                1.3.2            py39hc89836e_5    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1003    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-blosc2                  2.0.4                ha1a4663_1    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
cffi                      1.15.0           py39he338e87_0    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
charls                    2.2.0                h046ec9c_0    conda-forge
charset-normalizer        2.0.10             pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39h6e9494a_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.1           py39h209aa08_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39h89e85a6_1    conda-forge
dask                      2021.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2021.12.0          pyhd8ed1ab_0    conda-forge
dask-glm                  0.2.0                      py_1    conda-forge
dask-image                2021.12.0          pyhd8ed1ab_0    conda-forge
dask-ml                   2021.11.30         pyhd8ed1ab_0    conda-forge
distributed               2021.12.0        py39h6e9494a_0    conda-forge
expat                     2.4.2                he49afe7_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h10f422b_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.5           py39h89e85a6_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
frozenlist                1.2.0            py39h89e85a6_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.6               h2e6141f_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glog                      0.5.0                h25b26a9_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
graphviz                  2.50.0               h77de9ca_1    conda-forge
grpc-cpp                  1.42.0               h6da9ac5_1    conda-forge
gtk2                      2.24.33              h675d97a_1    conda-forge
gts                       0.7.6                hccb3bdf_2    conda-forge
h5py                      3.6.0           nompi_py39hbc6cb89_100    conda-forge
harfbuzz                  3.2.0                h447b35c_0    conda-forge
hdf5                      1.12.1          nompi_h2f0ef1a_103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.11.20       py39h90d8905_1    conda-forge
importlib-metadata        4.10.0           py39h6e9494a_0    conda-forge
importlib_metadata        4.10.0               hd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.3.2            py39hf018cea_1    conda-forge
krb5                      1.19.2               hcfbf3a7_3    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libblas                   3.9.0           12_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           12_osx64_openblas    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libdeflate                1.8                  h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h815e4d9_4    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgd                     2.3.3                hb8742e1_1    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           12_osx64_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnghttp2                1.43.0               h6f36284_1    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libprotobuf               3.19.2               hcf210ce_0    conda-forge
librsvg                   2.52.5               h02b643e_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libthrift                 0.15.0               hab56fdc_1    conda-forge
libtiff                   4.3.0                hd146c10_2    conda-forge
libtool                   2.4.6             he49afe7_1008    conda-forge
libutf8proc               2.7.0                h0d85af4_0    conda-forge
libwebp                   1.2.1                h28dabe5_0    conda-forge
libwebp-base              1.2.1                h0d85af4_0    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
llvmlite                  0.36.0           py39h798a4f4_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4                       3.1.10           py39heb8eec3_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.0.1            py39h89e85a6_1    conda-forge
matplotlib-base           3.5.1            py39hb07454d_0    conda-forge
msgpack-python            1.0.3            py39hf018cea_0    conda-forge
multidict                 5.2.0            py39h89e85a6_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
numba                     0.53.1           py39h32e38f5_1    conda-forge
numpy                     1.22.0           py39h9d9ce41_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
orc                       1.7.2                h84518c8_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py39h4d6be9b_0    conda-forge
pango                     1.48.10              h056538c_2    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pillow                    8.4.0            py39he9bb72f_0    conda-forge
pims                      0.5                pyh9f0ad1d_1    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
psutil                    5.9.0            py39h89e85a6_0    conda-forge
pyarrow                   6.0.1           py39h4d6536f_7_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_4    conda-forge
python                    3.9.9           h1248fe1_0_cpython    conda-forge
python-blosc              1.10.2           py39h4d6be9b_2    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.19.1             pyhaef67bd_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h89e85a6_3    conda-forge
re2                       2021.11.01           he49afe7_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
s3fs                      2021.11.1          pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py39hd4eea88_0    conda-forge
scipy                     1.7.3            py39h056f1c0_0    conda-forge
setuptools                60.5.0           py39h6e9494a_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.0.0                      py_0    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h89e85a6_2    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.3           py39h89e85a6_1    conda-forge
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yarl                      1.7.2            py39h89e85a6_1    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.7.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.1                h582d3a0_0    conda-forge
```

Seems to match the solve listed in this issue: https://gitlab.com/coiled/cloud/-/issues/4284

```
C:\Users\greg\anaconda3\envs\shakedown-39\lib\site-packages\distributed\client.py:1096: VersionMismatchWarning: Mismatched versions found
+-------------+---------------+---------------+---------------+
| Package     | client        | scheduler     | workers       |
+-------------+---------------+---------------+---------------+
| dask        | 2021.12.0     | 2021.11.2     | 2021.11.2     |
| distributed | 2021.12.0     | 2021.11.2     | 2021.11.2     |
| numpy       | 1.22.0        | 1.21.4        | 1.21.4        |
| pandas      | 1.3.5         | 1.3.4         | 1.3.4         |
| python      | 3.9.9.final.0 | 3.9.7.final.0 | 3.9.7.final.0 |
+-------------+---------------+---------------+---------------+
```

### CODE REVIEW

**Comment by matthiasdv** [comment]
Hmmm, not exactly sure why 3.7 and 3.9 are failing against staging.

**Comment by FabioRosado** [comment]
That's because the account ran out of cores, we need to bump the account limits, do you know which account is running these tests?

**Comment by dafabulousteach** [comment]
@ian-r-rose has set the quota to be 0 and I re-ran the tests

**Review by ian-r-rose — APPROVED** [review]
LGTM. This supersedes #55

**Comment by matthiasdv** [comment]
Thanks @ian-r-rose !

**Pull request merged**
